/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aktepeyazilim;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;

/**
 *
 * @author uğur
 */
public class Ornek_019_jTree_Kontrolu extends javax.swing.JFrame {

	/**
	 * Creates new form Ornek_019_jTree_Kontrolu
	 */
//	private DefaultMutableTreeNode kokElemani;
//	private DefaultTreeModel agacListemizinModeli;
//	private DefaultMutableTreeNode altKategori1, altKategori2;
	public Ornek_019_jTree_Kontrolu() {
		initComponents();
		DefaultMutableTreeNode kokElemani = new DefaultMutableTreeNode("KÖK ELEMANI");
		TreeModel agacListemizinModeli = new DefaultTreeModel(kokElemani);
		jTree1.setModel(agacListemizinModeli);
		
		DefaultMutableTreeNode altKategori1 = new DefaultMutableTreeNode("ALT KATEGORİ1");
		kokElemani.add(altKategori1);
		
		DefaultMutableTreeNode altKategori2 = new DefaultMutableTreeNode("ALT KATEGORİ2");
		kokElemani.add(altKategori2);
		
		Icon ictekiAltKategori = new ImageIcon(getClass().getResource("/images/World.png"));
		Icon kapaliDurum = new ImageIcon(getClass().getResource("/images/X.png"));
		Icon acikDurum = new ImageIcon(getClass().getResource("/images/Checkmark.png"));
		DefaultTreeCellRenderer renderer = (DefaultTreeCellRenderer) jTree1.getCellRenderer();
		renderer.setLeafIcon(ictekiAltKategori);
		renderer.setClosedIcon(kapaliDurum);
		renderer.setOpenIcon(acikDurum);
		
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

                jSplitPane1 = new javax.swing.JSplitPane();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTree2 = new javax.swing.JTree();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTree1 = new javax.swing.JTree();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jSplitPane1.setDividerLocation(200);

                org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTree1, org.jdesktop.beansbinding.ELProperty.create("${border}"), jTree2, org.jdesktop.beansbinding.BeanProperty.create("border"));
                bindingGroup.addBinding(binding);
                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTree1, org.jdesktop.beansbinding.ELProperty.create("${model}"), jTree2, org.jdesktop.beansbinding.BeanProperty.create("model"));
                bindingGroup.addBinding(binding);

                jScrollPane2.setViewportView(jTree2);

                jSplitPane1.setRightComponent(jScrollPane2);

                jTree1.setBackground(new java.awt.Color(255, 255, 204));
                jTree1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "JAVA GUI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 51, 51))); // NOI18N
                javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
                javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("YAZILIM FİRMAMIZ");
                javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Yönetim Kurulu");
                javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Uğur Arı");
                treeNode3.add(treeNode4);
                treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Zülfü Arı");
                treeNode3.add(treeNode4);
                treeNode2.add(treeNode3);
                treeNode1.add(treeNode2);
                treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Bilgisayar Mühendisleri");
                treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Muhammed Ali Arı");
                treeNode2.add(treeNode3);
                treeNode1.add(treeNode2);
                treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Yazılım Mühendisleri");
                treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Zülfiye Arı");
                treeNode2.add(treeNode3);
                treeNode1.add(treeNode2);
                jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
                jTree1.setEditable(true);
                jScrollPane1.setViewportView(jTree1);

                jSplitPane1.setLeftComponent(jScrollPane1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(245, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(339, Short.MAX_VALUE))
                );

                bindingGroup.bind();

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Ornek_019_jTree_Kontrolu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Ornek_019_jTree_Kontrolu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Ornek_019_jTree_Kontrolu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Ornek_019_jTree_Kontrolu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Ornek_019_jTree_Kontrolu().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JSplitPane jSplitPane1;
        private javax.swing.JTree jTree1;
        private javax.swing.JTree jTree2;
        private org.jdesktop.beansbinding.BindingGroup bindingGroup;
        // End of variables declaration//GEN-END:variables
}
