/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aktepeyazilim;

import java.awt.event.ItemEvent;

/**
 *
 * @author uğur
 */
public class Ornek_006_jGrupButton_Kontrolu extends javax.swing.JFrame {

	/**
	 * Creates new form Ornek_006_jGrupButton_Kontrolu
	 */
	public Ornek_006_jGrupButton_Kontrolu() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

                buttonGroup1 = new javax.swing.ButtonGroup();
                buttonGroup2 = new javax.swing.ButtonGroup();
                buttonGroup3 = new javax.swing.ButtonGroup();
                buttonGroup4 = new javax.swing.ButtonGroup();
                buttonGroup5 = new javax.swing.ButtonGroup();
                jToggleButton1 = new javax.swing.JToggleButton();
                jToggleButton2 = new javax.swing.JToggleButton();
                jToggleButton3 = new javax.swing.JToggleButton();
                jToggleButton4 = new javax.swing.JToggleButton();
                jCheckBox1 = new javax.swing.JCheckBox();
                jCheckBox2 = new javax.swing.JCheckBox();
                jCheckBox3 = new javax.swing.JCheckBox();
                jCheckBox4 = new javax.swing.JCheckBox();
                jRadioButton1 = new javax.swing.JRadioButton();
                jRadioButton2 = new javax.swing.JRadioButton();
                jRadioButton3 = new javax.swing.JRadioButton();
                jRadioButton4 = new javax.swing.JRadioButton();
                jPanel1 = new javax.swing.JPanel();
                jRadioButton5 = new javax.swing.JRadioButton();
                jRadioButton6 = new javax.swing.JRadioButton();
                jRadioButton7 = new javax.swing.JRadioButton();
                jRadioButton8 = new javax.swing.JRadioButton();
                jPanel2 = new javax.swing.JPanel();
                jRadioButton9 = new javax.swing.JRadioButton();
                jRadioButton10 = new javax.swing.JRadioButton();
                jButton1 = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                buttonGroup1.add(jToggleButton1);
                jToggleButton1.setText("jToggleButton1");

                buttonGroup1.add(jToggleButton2);
                jToggleButton2.setText("jToggleButton2");

                buttonGroup1.add(jToggleButton3);
                jToggleButton3.setText("jToggleButton3");

                buttonGroup1.add(jToggleButton4);
                jToggleButton4.setText("jToggleButton4");

                buttonGroup2.add(jCheckBox1);
                jCheckBox1.setText("jCheckBox1");

                buttonGroup2.add(jCheckBox2);
                jCheckBox2.setText("jCheckBox2");

                buttonGroup2.add(jCheckBox3);
                jCheckBox3.setText("jCheckBox3");

                buttonGroup2.add(jCheckBox4);
                jCheckBox4.setText("jCheckBox4");

                buttonGroup3.add(jRadioButton1);
                jRadioButton1.setText("jRadioButton1");

                buttonGroup3.add(jRadioButton2);
                jRadioButton2.setText("jRadioButton2");

                buttonGroup3.add(jRadioButton3);
                jRadioButton3.setText("jRadioButton3");

                buttonGroup3.add(jRadioButton4);
                jRadioButton4.setText("jRadioButton4");

                jPanel1.setBackground(new java.awt.Color(255, 255, 204));
                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kan Grupları", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 51))); // NOI18N

                buttonGroup4.add(jRadioButton5);
                jRadioButton5.setText("A");

                org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jRadioButton5, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jRadioButton5.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                jRadioButton5İtemStateChanged(evt);
                        }
                });

                buttonGroup4.add(jRadioButton6);
                jRadioButton6.setText("B");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jRadioButton6, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jRadioButton6.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                jRadioButton6İtemStateChanged(evt);
                        }
                });

                buttonGroup4.add(jRadioButton7);
                jRadioButton7.setText("AB");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jRadioButton7, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jRadioButton7.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                jRadioButton7İtemStateChanged(evt);
                        }
                });

                buttonGroup4.add(jRadioButton8);
                jRadioButton8.setText("0");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jRadioButton8, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jRadioButton8.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                jRadioButton8İtemStateChanged(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton5)
                                        .addComponent(jRadioButton6)
                                        .addComponent(jRadioButton7)
                                        .addComponent(jRadioButton8))
                                .addGap(0, 90, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jRadioButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                                .addComponent(jRadioButton8))
                );

                jPanel2.setBackground(new java.awt.Color(255, 255, 153));
                jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Negatif-Pozitif Durumu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 51))); // NOI18N

                buttonGroup5.add(jRadioButton9);
                jRadioButton9.setText("Pozitif(+)");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel2, org.jdesktop.beansbinding.ELProperty.create("${background}"), jRadioButton9, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jRadioButton9.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                jRadioButton9İtemStateChanged(evt);
                        }
                });

                buttonGroup5.add(jRadioButton10);
                jRadioButton10.setText("Negatif(-)");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel2, org.jdesktop.beansbinding.ELProperty.create("${background}"), jRadioButton10, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jRadioButton10.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                jRadioButton10İtemStateChanged(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton9)
                                        .addComponent(jRadioButton10))
                                .addContainerGap(72, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jRadioButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton10)
                                .addContainerGap(56, Short.MAX_VALUE))
                );

                jButton1.setText("Tamamla");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jLabel1.setText("Kan Grubunuz: ");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButton1)
                                                        .addComponent(jLabel1)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jToggleButton1)
                                                        .addComponent(jToggleButton2)
                                                        .addComponent(jToggleButton3)
                                                        .addComponent(jToggleButton4))
                                                .addGap(30, 30, 30)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jCheckBox1)
                                                        .addComponent(jCheckBox2)
                                                        .addComponent(jCheckBox3)
                                                        .addComponent(jCheckBox4))
                                                .addGap(27, 27, 27)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jRadioButton4)
                                                        .addComponent(jRadioButton3)
                                                        .addComponent(jRadioButton1)
                                                        .addComponent(jRadioButton2))))
                                .addContainerGap(74, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jToggleButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jToggleButton2)
                                                        .addComponent(jCheckBox2))
                                                .addGap(11, 11, 11)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jToggleButton3)
                                                        .addComponent(jCheckBox3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jToggleButton4)
                                                        .addComponent(jCheckBox4)
                                                        .addComponent(jRadioButton4)))
                                        .addComponent(jCheckBox1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(jRadioButton2)
                                                .addGap(11, 11, 11)
                                                .addComponent(jRadioButton3))
                                        .addComponent(jRadioButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(13, 13, 13)
                                                        .addComponent(jButton1)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel1))
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(53, Short.MAX_VALUE))
                );

                bindingGroup.bind();

                pack();
        }// </editor-fold>//GEN-END:initComponents
String kanGrubu = null, artieksi = null,sonuc = null;
        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                
		
		sonuc = "Kan Grubunuz: " + kanGrubu + " " + artieksi;
		jLabel1.setText(sonuc);
		
		
		
        }//GEN-LAST:event_jButton1ActionPerformed

        private void jRadioButton5İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton5İtemStateChanged
               if(evt.getStateChange()==ItemEvent.SELECTED)
	       {
		       kanGrubu = jRadioButton5.getText();
	       }
        }//GEN-LAST:event_jRadioButton5İtemStateChanged

        private void jRadioButton6İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton6İtemStateChanged
                if(evt.getStateChange()==ItemEvent.SELECTED)
	       {
		       kanGrubu = jRadioButton6.getText();
	       }
        }//GEN-LAST:event_jRadioButton6İtemStateChanged

        private void jRadioButton7İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton7İtemStateChanged
               if(evt.getStateChange()==ItemEvent.SELECTED)
	       {
		       kanGrubu = jRadioButton7.getText();
	       }
        }//GEN-LAST:event_jRadioButton7İtemStateChanged

        private void jRadioButton8İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton8İtemStateChanged
                if(evt.getStateChange()==ItemEvent.SELECTED)
	       {
		       kanGrubu = jRadioButton8.getText();
	       }
        }//GEN-LAST:event_jRadioButton8İtemStateChanged

        private void jRadioButton9İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton9İtemStateChanged
                if(evt.getStateChange()==ItemEvent.SELECTED)
	       {
		       artieksi = jRadioButton9.getText();
	       }else{
			artieksi = jRadioButton10.getText();
		}
        }//GEN-LAST:event_jRadioButton9İtemStateChanged

        private void jRadioButton10İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton10İtemStateChanged
               
        }//GEN-LAST:event_jRadioButton10İtemStateChanged

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Ornek_006_jGrupButton_Kontrolu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Ornek_006_jGrupButton_Kontrolu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Ornek_006_jGrupButton_Kontrolu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Ornek_006_jGrupButton_Kontrolu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Ornek_006_jGrupButton_Kontrolu().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.ButtonGroup buttonGroup2;
        private javax.swing.ButtonGroup buttonGroup3;
        private javax.swing.ButtonGroup buttonGroup4;
        private javax.swing.ButtonGroup buttonGroup5;
        private javax.swing.JButton jButton1;
        private javax.swing.JCheckBox jCheckBox1;
        private javax.swing.JCheckBox jCheckBox2;
        private javax.swing.JCheckBox jCheckBox3;
        private javax.swing.JCheckBox jCheckBox4;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JRadioButton jRadioButton1;
        private javax.swing.JRadioButton jRadioButton10;
        private javax.swing.JRadioButton jRadioButton2;
        private javax.swing.JRadioButton jRadioButton3;
        private javax.swing.JRadioButton jRadioButton4;
        private javax.swing.JRadioButton jRadioButton5;
        private javax.swing.JRadioButton jRadioButton6;
        private javax.swing.JRadioButton jRadioButton7;
        private javax.swing.JRadioButton jRadioButton8;
        private javax.swing.JRadioButton jRadioButton9;
        private javax.swing.JToggleButton jToggleButton1;
        private javax.swing.JToggleButton jToggleButton2;
        private javax.swing.JToggleButton jToggleButton3;
        private javax.swing.JToggleButton jToggleButton4;
        private org.jdesktop.beansbinding.BindingGroup bindingGroup;
        // End of variables declaration//GEN-END:variables
}
