/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aktepeyazilim;

/**
 *
 * @author uğur
 */
public class Ornek_003_jToggleButton_Kontrolu extends javax.swing.JFrame {

	/**
	 * Creates new form Ornek_003_jToggleButton_Kontrolu
	 */
	public Ornek_003_jToggleButton_Kontrolu() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup1 = new javax.swing.ButtonGroup();
                buttonGroup2 = new javax.swing.ButtonGroup();
                jToggleButton1 = new javax.swing.JToggleButton();
                jToggleButton2 = new javax.swing.JToggleButton();
                jToggleButton3 = new javax.swing.JToggleButton();
                jToggleButton4 = new javax.swing.JToggleButton();
                jToggleButton5 = new javax.swing.JToggleButton();
                jRadioButton1 = new javax.swing.JRadioButton();
                jCheckBox1 = new javax.swing.JCheckBox();
                jRadioButton2 = new javax.swing.JRadioButton();
                jRadioButton3 = new javax.swing.JRadioButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("jToggle Button");

                buttonGroup1.add(jToggleButton1);
                jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jToggleButton1.setForeground(new java.awt.Color(255, 102, 0));
                jToggleButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\uğur\\Documents\\NetBeansProjects\\Java_GUI_Swing_Control\\src\\images\\Heart.png")); // NOI18N
                jToggleButton1.setText("Sarışın");
                jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                jToggleButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Checkmark.png"))); // NOI18N
                jToggleButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Heart-add.png"))); // NOI18N

                jToggleButton2.setBackground(new java.awt.Color(102, 255, 0));
                buttonGroup1.add(jToggleButton2);
                jToggleButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jToggleButton2.setForeground(new java.awt.Color(102, 0, 0));
                jToggleButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\uğur\\Documents\\NetBeansProjects\\Java_GUI_Swing_Control\\src\\images\\Heart.png")); // NOI18N
                jToggleButton2.setText("Esmer");

                buttonGroup1.add(jToggleButton3);
                jToggleButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jToggleButton3.setForeground(new java.awt.Color(153, 102, 0));
                jToggleButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\uğur\\Documents\\NetBeansProjects\\Java_GUI_Swing_Control\\src\\images\\Heart.png")); // NOI18N
                jToggleButton3.setText("Kumral");

                jToggleButton4.setText("jToggleButton4");

                jToggleButton5.setText("jToggleButton5");

                buttonGroup2.add(jRadioButton1);
                jRadioButton1.setText("jRadioButton1");

                jCheckBox1.setText("jCheckBox1");

                buttonGroup2.add(jRadioButton2);
                jRadioButton2.setText("jRadioButton2");

                buttonGroup2.add(jRadioButton3);
                jRadioButton3.setText("jRadioButton3");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jToggleButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton3)
                                        .addComponent(jRadioButton2)
                                        .addComponent(jRadioButton1))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jToggleButton5)
                                                .addComponent(jToggleButton4))
                                        .addComponent(jCheckBox1))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addComponent(jToggleButton4)
                                                .addGap(18, 18, 18)
                                                .addComponent(jToggleButton5)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCheckBox1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(78, 78, 78)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jToggleButton2)
                                                                        .addComponent(jRadioButton2)))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jToggleButton1)
                                                                .addComponent(jRadioButton1)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jToggleButton3))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(29, 29, 29)
                                                                .addComponent(jRadioButton3)))))
                                .addContainerGap(393, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Ornek_003_jToggleButton_Kontrolu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Ornek_003_jToggleButton_Kontrolu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Ornek_003_jToggleButton_Kontrolu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Ornek_003_jToggleButton_Kontrolu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Ornek_003_jToggleButton_Kontrolu().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.ButtonGroup buttonGroup2;
        private javax.swing.JCheckBox jCheckBox1;
        private javax.swing.JRadioButton jRadioButton1;
        private javax.swing.JRadioButton jRadioButton2;
        private javax.swing.JRadioButton jRadioButton3;
        private javax.swing.JToggleButton jToggleButton1;
        private javax.swing.JToggleButton jToggleButton2;
        private javax.swing.JToggleButton jToggleButton3;
        private javax.swing.JToggleButton jToggleButton4;
        private javax.swing.JToggleButton jToggleButton5;
        // End of variables declaration//GEN-END:variables
}
