-package tr.com.siteadi001.mysqlbaglantisi;

import com.mysql.jdbc.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.design.*;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author uğur
 */
public class YoneticiFormuGUI extends javax.swing.JFrame {

	/**
	 * Creates new form YoneticiFormuGUI
	 */
	public YoneticiFormuGUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup1 = new javax.swing.ButtonGroup();
                btnSil = new javax.swing.JButton();
                btnGuncelle = new javax.swing.JButton();
                btnKaydet = new javax.swing.JButton();
                btnTemizle = new javax.swing.JButton();
                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                lblAramaAdi = new javax.swing.JLabel();
                txtAramaAdi = new javax.swing.JTextField();
                txtAramaSoyadi = new javax.swing.JTextField();
                lblAramaSoyadi = new javax.swing.JLabel();
                lblAramaMeslegi = new javax.swing.JLabel();
                cbAramaMeslegi = new javax.swing.JComboBox<>();
                jScrollPane2 = new javax.swing.JScrollPane();
                txtEklenenKayit = new javax.swing.JTextArea();
                jPanel4 = new javax.swing.JPanel();
                lblProje = new javax.swing.JLabel();
                txtSoyadi = new javax.swing.JTextField();
                cbYasi = new javax.swing.JComboBox<>();
                lblSoyadi = new javax.swing.JLabel();
                lblTelefonu = new javax.swing.JLabel();
                txtUzmanlikAlani = new javax.swing.JTextField();
                lblMeslegi = new javax.swing.JLabel();
                rbEhliyetYok = new javax.swing.JRadioButton();
                lblAdi = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                cbTecrubeYili = new javax.swing.JComboBox<>();
                txtTelefonu = new javax.swing.JTextField();
                rbEhliyetVar = new javax.swing.JRadioButton();
                txtAdi = new javax.swing.JTextField();
                cbMeslegi = new javax.swing.JComboBox<>();
                lblTecrube = new javax.swing.JLabel();
                cboxProje = new javax.swing.JCheckBox();
                jLabel2 = new javax.swing.JLabel();
                lblEhliyet = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jButton1 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Yönetici FOrmu");
                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowClosed(java.awt.event.WindowEvent evt) {
                                formWindowClosed(evt);
                        }
                        public void windowOpened(java.awt.event.WindowEvent evt) {
                                formWindowOpened(evt);
                        }
                });

                btnSil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                btnSil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Person-white-x.png"))); // NOI18N
                btnSil.setText("Sil");
                btnSil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnSil.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSilActionPerformed(evt);
                        }
                });

                btnGuncelle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                btnGuncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Person-white-warning.png"))); // NOI18N
                btnGuncelle.setText("Güncelle");
                btnGuncelle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnGuncelle.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnGuncelleActionPerformed(evt);
                        }
                });

                btnKaydet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                btnKaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Person-white-add.png"))); // NOI18N
                btnKaydet.setText("Kaydet");
                btnKaydet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnKaydet.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnKaydetActionPerformed(evt);
                        }
                });

                btnTemizle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                btnTemizle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Refresh.png"))); // NOI18N
                btnTemizle.setText("Temizler");
                btnTemizle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                btnTemizle.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnTemizleActionPerformed(evt);
                        }
                });

                jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                jPanel1KeyReleased(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                lblAramaAdi.setText("Adı");

                txtAramaAdi.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                txtAramaAdiKeyReleased(evt);
                        }
                });

                txtAramaSoyadi.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                txtAramaAdiKeyReleased(evt);
                        }
                });

                lblAramaSoyadi.setText("Soyadi");

                lblAramaMeslegi.setText("Meslegi");

                cbAramaMeslegi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "***", "Stajyer", "Teknisyen", "Bilgisayar Mühendisi", "Yazılım Mühendisi", "Veri Mühendisi", "Ağ Mühendisi", "Laboratuvar Teknikeri", "İktisat" }));
                cbAramaMeslegi.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                cbAramaMeslegiİtemStateChanged(evt);
                        }
                });

                txtEklenenKayit.setColumns(20);
                txtEklenenKayit.setRows(5);
                jScrollPane2.setViewportView(txtEklenenKayit);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblAramaMeslegi)
                                        .addComponent(lblAramaAdi))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtAramaAdi)
                                                .addComponent(cbAramaMeslegi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtAramaSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lblAramaSoyadi)
                                        .addGap(311, 311, 311)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtAramaAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblAramaAdi))
                                .addGap(18, 18, 18)
                                .addComponent(txtAramaSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbAramaMeslegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblAramaMeslegi))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap(38, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblAramaSoyadi, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(69, 69, 69)))
                );

                lblProje.setText("Proje");

                cbYasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41" }));

                lblSoyadi.setText("Soyadi");

                lblTelefonu.setText("Telefon");

                lblMeslegi.setText("Meslegi");

                buttonGroup1.add(rbEhliyetYok);
                rbEhliyetYok.setText("Yok");

                lblAdi.setText("Adı");

                jLabel1.setText("Yaşı");

                cbTecrubeYili.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

                buttonGroup1.add(rbEhliyetVar);
                rbEhliyetVar.setText("Var");

                cbMeslegi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "***", "Stajyer", "Teknisyen", "Bilgisayar Mühendisi", "Yazılım Mühendisi", "Veri Mühendisi", "Ağ Mühendisi" }));

                lblTecrube.setText("Tecrübe Yılı");

                cboxProje.setSelected(true);
                cboxProje.setText("Var");

                jLabel2.setText("Uzmanlık Alanı");

                lblEhliyet.setText("Ehliyet");

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblAdi)
                                        .addComponent(lblSoyadi)
                                        .addComponent(lblTelefonu)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(lblMeslegi)
                                        .addComponent(lblTecrube)
                                        .addComponent(lblEhliyet)
                                        .addComponent(lblProje))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbTecrubeYili, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbMeslegi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTelefonu)
                                        .addComponent(txtAdi)
                                        .addComponent(cbYasi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtSoyadi)
                                        .addComponent(txtUzmanlikAlani)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(rbEhliyetVar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rbEhliyetYok))
                                        .addComponent(cboxProje))
                                .addContainerGap())
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblAdi)
                                        .addComponent(txtAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblSoyadi)
                                        .addComponent(txtSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(cbYasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblTelefonu)
                                        .addComponent(txtTelefonu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtUzmanlikAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbMeslegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblMeslegi))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbTecrubeYili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTecrube))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblEhliyet)
                                        .addComponent(rbEhliyetVar)
                                        .addComponent(rbEhliyetYok))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblProje)
                                        .addComponent(cboxProje))
                                .addContainerGap())
                );

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jTable1MouseClicked(evt);
                        }
                });
                jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                jTable1KeyPressed(evt);
                        }
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                jTable1KeyReleased(evt);
                        }
                });
                jScrollPane1.setViewportView(jTable1);

                jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Address-book.png"))); // NOI18N
                jButton1.setText("YAZDIR");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1087, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(32, 32, 32)
                                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(btnSil)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(btnKaydet)
                                                                                .addGap(2, 2, 2)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(btnGuncelle)
                                                                                        .addComponent(btnTemizle))))
                                                                .addGap(40, 40, 40)
                                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                );

                layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnGuncelle, btnKaydet, btnSil, btnTemizle});

                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnSil)
                                                        .addComponent(btnGuncelle)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnKaydet)
                                                        .addComponent(btnTemizle))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
      
                        
        Connection baglanti = null;
	ResultSet resultSet = null;
	Statement statement = null;
	PreparedStatement preparedStatement = null;
	CallableStatement callableStatement = null;
      
        private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
               baglanti = mysqlBaglantisi.baglanti();
		tabloyuGuncelle();
		sonEklenen5Kayit();
        }//GEN-LAST:event_formWindowOpened

        private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            tabloyuDoldur();
        }//GEN-LAST:event_jTable1MouseClicked

        private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
                 tabloyuDoldur();
        }//GEN-LAST:event_jTable1KeyPressed

        private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
               tabloyuDoldur();
        }//GEN-LAST:event_jTable1KeyReleased

        private void cbAramaMeslegiİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAramaMeslegiİtemStateChanged
                aramaYap();
        }//GEN-LAST:event_cbAramaMeslegiİtemStateChanged

        private void txtAramaAdiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAramaAdiKeyReleased
                aramaYap();
		
        }//GEN-LAST:event_txtAramaAdiKeyReleased

        private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
                kaydetNormalla();
        }//GEN-LAST:event_btnKaydetActionPerformed

        private void btnTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemizleActionPerformed
               formuTemizle();
        }//GEN-LAST:event_btnTemizleActionPerformed

        private void btnGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncelleActionPerformed
             //guncelleNormalYolla();      
	     guncelleProsedurle();
        }//GEN-LAST:event_btnGuncelleActionPerformed

        private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
                silNormalYolla();
        }//GEN-LAST:event_btnSilActionPerformed

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                try{
			
			
			String ADI =  txtAramaAdi.getText()+"%";
			String SOYADI =  txtAramaAdi.getText()+"%";
			String MESLEGI = null;		
			if("***".equals(cbAramaMeslegi.getSelectedItem().toString())){
			//preparedStatement.setString(3, "%");
			MESLEGI = "%";	
			}else{
			MESLEGI = "%"+cbAramaMeslegi.getSelectedItem().toString()+"%";	
			}
			
			
			String raporSorgusu = "SELECT * FROM sirket.kisiler WHERE adi LIKE '"+ADI+"' AND soyadi LIKE '"+SOYADI+"' AND meslegi LIKE '"+MESLEGI+"'";
			
			JasperDesign jasperDesign = JRXmlLoader.load("report1.jrxml");
			//String raporSorgusu = "SELECT * FROM sirket.kisiler";
			JRDesignQuery designQuery = new JRDesignQuery();
			designQuery.setText(raporSorgusu);
			jasperDesign.setQuery(designQuery);
			JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
			JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,null, baglanti);
			JasperViewer.viewReport(jasperPrint,false);
			
		}catch(Exception e){
			System.out.println("Hata: "+e);
		}
        }//GEN-LAST:event_jButton1ActionPerformed

        private void jPanel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyReleased
            
        }//GEN-LAST:event_jPanel1KeyReleased

        private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
              if(baglanti != null){
			try{
				baglanti.close();
			}catch(Exception e){
				
			}
		}
		
		 if(resultSet != null){
			try{
				resultSet.close();
			}catch(Exception e){
				
			}
		}
		 
		  if(preparedStatement != null){
			try{
				preparedStatement.close();
			}catch(Exception e){
				
			}
		}
        }                                   

        private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
                  
		  
        }//GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	@SuppressWarnings("unchecked")
	
     
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(YoneticiFormuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(YoneticiFormuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(YoneticiFormuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(YoneticiFormuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new YoneticiFormuGUI().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnGuncelle;
        private javax.swing.JButton btnKaydet;
        private javax.swing.JButton btnSil;
        private javax.swing.JButton btnTemizle;
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JComboBox<String> cbAramaMeslegi;
        private javax.swing.JComboBox<String> cbMeslegi;
        private javax.swing.JComboBox<String> cbTecrubeYili;
        private javax.swing.JComboBox<String> cbYasi;
        private javax.swing.JCheckBox cboxProje;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTable jTable1;
        private javax.swing.JLabel lblAdi;
        private javax.swing.JLabel lblAramaAdi;
        private javax.swing.JLabel lblAramaMeslegi;
        private javax.swing.JLabel lblAramaSoyadi;
        private javax.swing.JLabel lblEhliyet;
        private javax.swing.JLabel lblMeslegi;
        private javax.swing.JLabel lblProje;
        private javax.swing.JLabel lblSoyadi;
        private javax.swing.JLabel lblTecrube;
        private javax.swing.JLabel lblTelefonu;
        private javax.swing.JRadioButton rbEhliyetVar;
        private javax.swing.JRadioButton rbEhliyetYok;
        private javax.swing.JTextField txtAdi;
        private javax.swing.JTextField txtAramaAdi;
        private javax.swing.JTextField txtAramaSoyadi;
        private javax.swing.JTextArea txtEklenenKayit;
        private javax.swing.JTextField txtSoyadi;
        private javax.swing.JTextField txtTelefonu;
        private javax.swing.JTextField txtUzmanlikAlani;
        // End of variables declaration//GEN-END:variables

	private void tabloyuGuncelle() {
				
		try {
			String tabloyuGuncellerSorgusu = "SELECT * FROM sirket.kisiler";
			preparedStatement = baglanti.prepareStatement(tabloyuGuncellerSorgusu);
			resultSet = preparedStatement.executeQuery();
			jTable1.setModel(DbUtils.resultSetToTableModel(resultSet));
		} catch (Exception e) {
		}
	}

	private void tabloyuDoldur() {
		   int satirNumarasi = jTable1.getSelectedRow();
	       
	       txtAdi.setText(jTable1.getModel().getValueAt(satirNumarasi, 1).toString());
	       txtSoyadi.setText(jTable1.getModel().getValueAt(satirNumarasi, 2).toString());
	       cbYasi.setSelectedItem(jTable1.getModel().getValueAt(satirNumarasi, 3).toString());
	       txtTelefonu.setText(jTable1.getModel().getValueAt(satirNumarasi, 4).toString());
	       cbMeslegi.setSelectedItem(jTable1.getModel().getValueAt(satirNumarasi, 5).toString());
	       txtUzmanlikAlani.setText(jTable1.getModel().getValueAt(satirNumarasi, 6).toString());
	       cbTecrubeYili.setSelectedItem(jTable1.getModel().getValueAt(satirNumarasi, 7).toString());
	       
	       if("1".equals(jTable1.getModel().getValueAt(satirNumarasi, 8).toString())){
		       rbEhliyetVar.setSelected(true);
	       }else{
		       rbEhliyetYok.setSelected(true);
	       }
	       
	        if("1".equals(jTable1.getModel().getValueAt(satirNumarasi, 9).toString())){
		      cboxProje.setSelected(true);
		      cboxProje.setText("VAR");
	       }else{
		      cboxProje.setSelected(false);
		      cboxProje.setText("Yok");
	       }
	}

	private void aramaYap() {
		try {
			formuTemizle();
			String aramaSorgusu = "SELECT * FROM sirket.kisiler WHERE adi LIKE ? AND soyadi LIKE ? AND meslegi LIKE ?";
			preparedStatement = baglanti.prepareStatement(aramaSorgusu);
			preparedStatement.setString(1, txtAramaAdi.getText()+"%");
			preparedStatement.setString(2, txtAramaSoyadi.getText()+"%");
			
			if("***".equals(cbAramaMeslegi.getSelectedItem().toString())){
			preparedStatement.setString(3, "%");
			}else{
			preparedStatement.setString(3, "%"+cbAramaMeslegi.getSelectedItem().toString()+"%");	
			}
			
			resultSet = preparedStatement.executeQuery();
			jTable1.setModel(DbUtils.resultSetToTableModel(resultSet));
			
		} catch (Exception e) {
		}
		
	}

	private void sonEklenen5Kayit() {
		txtEklenenKayit.setText(null);
		try {
			preparedStatement = baglanti.prepareStatement("SELECT * FROM sirket.sonEklenen5KayitGetirView");
			resultSet = preparedStatement.executeQuery();
			
			while(resultSet.next()){
				int KISIID = resultSet.getInt("kisilerID");
				String ADI = resultSet.getString("adi");
				String SOYADI = resultSet.getString("soyadi");
				txtEklenenKayit.replaceSelection(KISIID + " " + ADI + " " + SOYADI + "\n");
			}
		
			
		} catch (Exception e) {
		}
	}

	private void kaydetPSile() {
		try {
			
			String ehliyetDurumu = "1";
			if(rbEhliyetVar.isSelected() == true){
				ehliyetDurumu = "1"; //Ehliyet Var
			}else{
				ehliyetDurumu = "0"; //Ehliyet Yok
			}
					
			String projeDurumu = "1";
			if(cboxProje.isSelected() == true){
				cboxProje.setText ("Var");
				projeDurumu = "1";
			}else{
				cboxProje.setText("Yok");
				projeDurumu = "0";
			}
			
			
			String eklemeSorgusu = 
"INSERT INTO `sirket`.`kisiler`(`adi`,`soyadi`,`yasi`,`telefon`,`meslegi`,`uzmanlikAlani`,`tecrubeYili`,`ehliyet`,`proje`)"+
"VALUES('"+txtAdi.getText()+"',"
    + "'"+ txtSoyadi.getText()+"',"
    + "'"+ cbYasi.getSelectedItem().toString()+"',"
    + "'"+ txtTelefonu.getText()+"',"				
    + "'"+ cbMeslegi.getSelectedItem().toString()+"',"	
    + "'"+ txtUzmanlikAlani.getText()+"',"		
    + "'"+ cbTecrubeYili.getSelectedItem().toString()+"',"
    + "'"+ ehliyetDurumu + "',"
    + "'"+ projeDurumu + "')";

				
			preparedStatement = baglanti.prepareStatement(eklemeSorgusu);		
			preparedStatement.execute();
			tabloyuGuncelle();
			sonEklenen5Kayit();
			formuTemizle();
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null,"HATA : " +e, "Mesaj", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void kaydetNormalla() {
		try {
			
			String ehliyetDurumu = "1";
			if(rbEhliyetVar.isSelected() == true){
				ehliyetDurumu = "1"; //Ehliyet Var
			}else{
				ehliyetDurumu = "0"; //Ehliyet Yok
			}
					
			String projeDurumu = "1";
			if(cboxProje.isSelected() == true){
				cboxProje.setText ("Var");
				projeDurumu = "1";
			}else{
				cboxProje.setText("Yok");
				projeDurumu = "0";
			}
			
			
			String eklemeSorgusu = 
"INSERT INTO `sirket`.`kisiler`(`adi`,`soyadi`,`yasi`,`telefon`,`meslegi`,`uzmanlikAlani`,`tecrubeYili`,`ehliyet`,`proje`)"+
"VALUES(?,?,?,?,?,?,?,?,?)";

				
			preparedStatement = baglanti.prepareStatement(eklemeSorgusu);	
		        preparedStatement.setString(1,txtAdi.getText());
			preparedStatement.setString(2,txtSoyadi.getText());
			preparedStatement.setInt(3,Integer.valueOf(cbYasi.getSelectedItem().toString()));
			preparedStatement.setString(4,txtTelefonu.getText());
			preparedStatement.setString(5,cbMeslegi.getSelectedItem().toString());
			preparedStatement.setString(6,txtUzmanlikAlani.getText());
			preparedStatement.setInt(7,Integer.parseInt(cbTecrubeYili.getSelectedItem().toString()));
			preparedStatement.setString(8,ehliyetDurumu);
			preparedStatement.setString(9,projeDurumu);
			
			preparedStatement.execute();
			tabloyuGuncelle();
			sonEklenen5Kayit();
			formuTemizle();
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null,"HATA : Ekleme Yapılamadı " , "Mesaj", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void formuTemizle() {
    txtAdi.setText(null);
    txtSoyadi.setText(null);
    cbYasi.setSelectedItem(0);
    txtTelefonu.setText(null);				
    cbMeslegi.setSelectedItem(0);	
    txtUzmanlikAlani.setText(null);		
    cbTecrubeYili.setSelectedItem(0);
    rbEhliyetVar.setSelected(true);
    cboxProje.setSelected(true);

	}

	private void guncelleNormalYolla() {
			try {
			
			String ehliyetDurumu = "1";
			if(rbEhliyetVar.isSelected() == true){
				ehliyetDurumu = "1"; //Ehliyet Var
			}else{
				ehliyetDurumu = "0"; //Ehliyet Yok
			}
					
			String projeDurumu = "1";
			if(cboxProje.isSelected() == true){
				cboxProje.setText ("Var");
				projeDurumu = "1";
			}else{
				cboxProje.setText("Yok");
				projeDurumu = "0";
			}
			
			
	String guncellemeSorgusu = "UPDATE `sirket`.`kisiler` SET "
	+ "`adi = `?, "
	+ "`soyadi` = ?, "
	+ "`yasi` = ?, "
        + "`telefon` = ?, "
	+ "`meslegi` = ?, "			
	+ "`uzmanlikAlani` = ?, "
	+ "`tecrubeYili` = ?, "
	+ "`ehliyet` = ?, "
	+ "`proje` = ? "
	+ "WHERE `kisilerId` = ?";
		
			preparedStatement = baglanti.prepareStatement(guncellemeSorgusu);		
			preparedStatement.setString(1, txtAdi.getText());
			preparedStatement.setString(2, txtSoyadi.getText());
			preparedStatement.setInt(3, Integer.valueOf(cbYasi.getSelectedItem().toString()));
			preparedStatement.setString(4, txtTelefonu.getText());
			preparedStatement.setString(5, cbMeslegi.getSelectedItem().toString());
			preparedStatement.setString(6, txtUzmanlikAlani.getText());
			preparedStatement.setInt(7, Integer.parseInt(cbTecrubeYili.getSelectedItem().toString()));
			preparedStatement.setString(8, ehliyetDurumu);
			preparedStatement.setString(9, projeDurumu);
		
			
			int satirNumarasi  = jTable1.getSelectedRow();
			preparedStatement.setString(10, jTable1.getModel().getValueAt(satirNumarasi, 0).toString());
			
			preparedStatement.executeUpdate();
			JOptionPane.showMessageDialog(null, "Güncelleme işlemi\n başarılı olarak gerçekleştirildi.","MESAJ",JOptionPane.ERROR_MESSAGE);
			tabloyuGuncelle();
		//	sonEklenen5Kayit();
			formuTemizle();
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null,"HATA : " +e, "Mesaj", JOptionPane.ERROR_MESSAGE);
		}
	}
	
	private void guncelleProsedurle() {
			try {
			
			String ehliyetDurumu = "1";
			if(rbEhliyetVar.isSelected() == true){
				ehliyetDurumu = "1"; //Ehliyet Var
			}else{
				ehliyetDurumu = "0"; //Ehliyet Yok
			}
					
			String projeDurumu = "1";
			if(cboxProje.isSelected() == true){
				cboxProje.setText ("Var");
				projeDurumu = "1";
			}else{
				cboxProje.setText("Yok");
				projeDurumu = "0";
			}
			
			
	String guncellemeSorgusu = "CALL sirket.kisilerGuncelle(?,?,?,?,?,?,?,?,?,?,?,?)";
		
			callableStatement = (CallableStatement) baglanti.prepareCall(guncellemeSorgusu);		
			callableStatement.setString(1,txtAdi.getText());
			callableStatement.setString(2,txtSoyadi.getText());
			callableStatement.setInt(3,Integer.valueOf(cbYasi.getSelectedItem().toString()));
			callableStatement.setString(4,txtTelefonu.getText());
			callableStatement.setString(5,cbMeslegi.getSelectedItem().toString());
			callableStatement.setString(6,txtUzmanlikAlani.getText());
			callableStatement.setInt(7,Integer.parseInt(cbTecrubeYili.getSelectedItem().toString()));
			callableStatement.setString(8,ehliyetDurumu);
			callableStatement.setString(9,projeDurumu);preparedStatement.setString(1,txtAdi.getText());
		
			
			int satirNumarasi  = jTable1.getSelectedRow();
			callableStatement.setString(10,jTable1.getModel().getValueAt(satirNumarasi, 0).toString());
			
			callableStatement.executeUpdate();
			JOptionPane.showMessageDialog(null, "Güncelleme işlemi\n başarılı olarak gerçekleştirildi.","MESAJ",JOptionPane.ERROR_MESSAGE);
			tabloyuGuncelle();
			sonEklenen5Kayit();
			formuTemizle();
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null,"HATA : " +e, "Mesaj", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void silNormalYolla(){
//		int gelenDeger = JOptionPane.showConfirmDialog(rootPane, "Emin Misiniz?","UYARI MESAJ", JOptionPane.WARNING_MESSAGE);
//		
//		if(gelenDeger == JOptionPane.YES_OPTION){
//			
//		}else if(gelenDeger == JOptionPane.NO_OPTION){
//			
//		}

            Object[] dugmeIsimleri = {"Evet Sil","Hayır Sil"};
	    int gelenDeger = JOptionPane.showOptionDialog(rootPane, "Emin misiniz?","UYARI MESAJI",
		    JOptionPane.YES_NO_OPTION,
		    JOptionPane.QUESTION_MESSAGE,
		    (new javax.swing.ImageIcon(getClass().getResource("/images/X.png"))),
	    dugmeIsimleri,dugmeIsimleri[1]);
	    
	    if(gelenDeger == 0){
		  
		try{	
			
			String silmeSorgusu = "DELETE FROM `sirket`.`kisiler`\n" +
"WHERE kisilerId = ? "; 

				
			preparedStatement = baglanti.prepareStatement(silmeSorgusu);	
			int satirNumarasi = jTable1.getSelectedRow();
			preparedStatement.setString(1, jTable1.getModel().getValueAt(satirNumarasi, 0).toString());
			preparedStatement.execute();
			JOptionPane.showMessageDialog(null, "Güncelleme işlemi\n başarılı olarak gerçekleştirildi.","MESAJ",JOptionPane.ERROR_MESSAGE);
			tabloyuGuncelle();
			sonEklenen5Kayit();
			formuTemizle();
	    }catch (Exception e) {
			JOptionPane.showMessageDialog(null,"HATA : " +e, "Mesaj", JOptionPane.ERROR_MESSAGE);
		}
	    
	    }else{
		    
	    }
	}

	
}
