/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.siteadi;

/**
 *
 * @author uğur
 */
public class Ornek_008_ScrollBar_Kontrolu extends javax.swing.JFrame {

	/**
	 * Creates new form Ornek_008_ScrollBar_Kontrolu
	 */
	public Ornek_008_ScrollBar_Kontrolu() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

                scrollPane1 = new java.awt.ScrollPane();
                panel1 = new java.awt.Panel();
                jCheckBox1 = new javax.swing.JCheckBox();
                jCheckBox2 = new javax.swing.JCheckBox();
                jCheckBox3 = new javax.swing.JCheckBox();
                jCheckBox4 = new javax.swing.JCheckBox();
                jCheckBox5 = new javax.swing.JCheckBox();
                jCheckBox6 = new javax.swing.JCheckBox();
                jCheckBox7 = new javax.swing.JCheckBox();
                jCheckBox8 = new javax.swing.JCheckBox();
                jCheckBox9 = new javax.swing.JCheckBox();
                jCheckBox10 = new javax.swing.JCheckBox();
                jCheckBox11 = new javax.swing.JCheckBox();
                jCheckBox12 = new javax.swing.JCheckBox();
                jCheckBox13 = new javax.swing.JCheckBox();
                jCheckBox14 = new javax.swing.JCheckBox();
                jScrollPane4 = new javax.swing.JScrollPane();
                jTree1 = new javax.swing.JTree();
                jScrollPane1 = new javax.swing.JScrollPane();
                jPanel2 = new javax.swing.JPanel();
                jCheckBox15 = new javax.swing.JCheckBox();
                jCheckBox16 = new javax.swing.JCheckBox();
                jCheckBox17 = new javax.swing.JCheckBox();
                jCheckBox18 = new javax.swing.JCheckBox();
                jCheckBox19 = new javax.swing.JCheckBox();
                jCheckBox20 = new javax.swing.JCheckBox();
                jCheckBox21 = new javax.swing.JCheckBox();
                jCheckBox22 = new javax.swing.JCheckBox();
                jCheckBox23 = new javax.swing.JCheckBox();
                jCheckBox24 = new javax.swing.JCheckBox();
                jCheckBox25 = new javax.swing.JCheckBox();
                jCheckBox26 = new javax.swing.JCheckBox();
                jCheckBox27 = new javax.swing.JCheckBox();
                jCheckBox28 = new javax.swing.JCheckBox();
                jScrollPane2 = new javax.swing.JScrollPane();
                jList1 = new javax.swing.JList<>();
                jScrollPane3 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();
                jLabel1 = new javax.swing.JLabel();
                label1 = new java.awt.Label();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                panel1.setBackground(new java.awt.Color(255, 153, 153));

                jCheckBox1.setText("jCheckBox1");

                org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, panel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox1, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox2.setText("jCheckBox2");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, panel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox2, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox3.setText("jCheckBox3");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, panel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox3, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox4.setText("jCheckBox4");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, panel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox4, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox5.setText("jCheckBox5");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, panel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox5, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox6.setText("jCheckBox6");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, panel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox6, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox7.setText("jCheckBox7");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, panel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox7, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox8.setText("jCheckBox8");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, panel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox8, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox9.setText("jCheckBox9");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, panel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox9, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox10.setText("jCheckBox10");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, panel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox10, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox11.setText("jCheckBox11");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, panel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox11, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox12.setText("jCheckBox12");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, panel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox12, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox13.setText("jCheckBox13");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, panel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox13, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox14.setText("jCheckBox14");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, panel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox14, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jScrollPane4.setViewportView(jTree1);

                javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
                panel1.setLayout(panel1Layout);
                panel1Layout.setHorizontalGroup(
                        panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBox14)
                                        .addComponent(jCheckBox3)
                                        .addComponent(jCheckBox4)
                                        .addComponent(jCheckBox5)
                                        .addComponent(jCheckBox6)
                                        .addComponent(jCheckBox7)
                                        .addComponent(jCheckBox1)
                                        .addComponent(jCheckBox2)
                                        .addComponent(jCheckBox8)
                                        .addComponent(jCheckBox9)
                                        .addComponent(jCheckBox10)
                                        .addComponent(jCheckBox11)
                                        .addComponent(jCheckBox12)
                                        .addComponent(jCheckBox13))
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(333, Short.MAX_VALUE))
                );
                panel1Layout.setVerticalGroup(
                        panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel1Layout.createSequentialGroup()
                                                .addComponent(jCheckBox1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jCheckBox14))
                                        .addComponent(jScrollPane4))
                                .addContainerGap())
                );

                scrollPane1.add(panel1);

                jPanel2.setBackground(new java.awt.Color(255, 204, 0));

                jCheckBox15.setText("jCheckBox14");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel2, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox15, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox16.setText("jCheckBox13");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel2, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox16, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox17.setText("jCheckBox11");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel2, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox17, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox18.setText("jCheckBox12");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel2, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox18, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox19.setText("jCheckBox10");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel2, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox19, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox20.setText("jCheckBox9");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel2, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox20, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox21.setText("jCheckBox8");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel2, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox21, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox22.setText("jCheckBox7");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel2, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox22, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox23.setText("jCheckBox6");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel2, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox23, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox24.setText("jCheckBox5");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel2, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox24, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox25.setText("jCheckBox4");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel2, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox25, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox26.setText("jCheckBox3");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel2, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox26, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox27.setText("jCheckBox2");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel2, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox27, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jCheckBox28.setText("jCheckBox1");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel2, org.jdesktop.beansbinding.ELProperty.create("${background}"), jCheckBox28, org.jdesktop.beansbinding.BeanProperty.create("background"));
                bindingGroup.addBinding(binding);

                jList1.setModel(new javax.swing.AbstractListModel<String>() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
                        public int getSize() { return strings.length; }
                        public String getElementAt(int i) { return strings[i]; }
                });
                jScrollPane2.setViewportView(jList1);

                jTextArea1.setColumns(20);
                jTextArea1.setRows(5);
                jScrollPane3.setViewportView(jTextArea1);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBox16)
                                        .addComponent(jCheckBox15)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jCheckBox23)
                                                        .addComponent(jCheckBox26)
                                                        .addComponent(jCheckBox25)
                                                        .addComponent(jCheckBox24)
                                                        .addComponent(jCheckBox28)
                                                        .addComponent(jCheckBox27)
                                                        .addComponent(jCheckBox22)
                                                        .addComponent(jCheckBox21)
                                                        .addComponent(jCheckBox20)
                                                        .addComponent(jCheckBox19)
                                                        .addComponent(jCheckBox17)
                                                        .addComponent(jCheckBox18))
                                                .addGap(65, 65, 65)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jScrollPane2)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))))
                                .addContainerGap(375, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jCheckBox28)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox27)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox26)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox25)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox24)
                                                .addGap(5, 5, 5)
                                                .addComponent(jCheckBox23))
                                        .addComponent(jScrollPane2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jCheckBox22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox20)
                                                .addGap(5, 5, 5)
                                                .addComponent(jCheckBox19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox18))
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox15)
                                .addContainerGap())
                );

                jScrollPane1.setViewportView(jPanel2);

                jLabel1.setText("SWING");

                label1.setText("AWT");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(231, 231, 231)
                                                .addComponent(jLabel1))
                                        .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(93, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                bindingGroup.bind();

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Ornek_008_ScrollBar_Kontrolu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Ornek_008_ScrollBar_Kontrolu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Ornek_008_ScrollBar_Kontrolu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Ornek_008_ScrollBar_Kontrolu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Ornek_008_ScrollBar_Kontrolu().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JCheckBox jCheckBox1;
        private javax.swing.JCheckBox jCheckBox10;
        private javax.swing.JCheckBox jCheckBox11;
        private javax.swing.JCheckBox jCheckBox12;
        private javax.swing.JCheckBox jCheckBox13;
        private javax.swing.JCheckBox jCheckBox14;
        private javax.swing.JCheckBox jCheckBox15;
        private javax.swing.JCheckBox jCheckBox16;
        private javax.swing.JCheckBox jCheckBox17;
        private javax.swing.JCheckBox jCheckBox18;
        private javax.swing.JCheckBox jCheckBox19;
        private javax.swing.JCheckBox jCheckBox2;
        private javax.swing.JCheckBox jCheckBox20;
        private javax.swing.JCheckBox jCheckBox21;
        private javax.swing.JCheckBox jCheckBox22;
        private javax.swing.JCheckBox jCheckBox23;
        private javax.swing.JCheckBox jCheckBox24;
        private javax.swing.JCheckBox jCheckBox25;
        private javax.swing.JCheckBox jCheckBox26;
        private javax.swing.JCheckBox jCheckBox27;
        private javax.swing.JCheckBox jCheckBox28;
        private javax.swing.JCheckBox jCheckBox3;
        private javax.swing.JCheckBox jCheckBox4;
        private javax.swing.JCheckBox jCheckBox5;
        private javax.swing.JCheckBox jCheckBox6;
        private javax.swing.JCheckBox jCheckBox7;
        private javax.swing.JCheckBox jCheckBox8;
        private javax.swing.JCheckBox jCheckBox9;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JList<String> jList1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JTextArea jTextArea1;
        private javax.swing.JTree jTree1;
        private java.awt.Label label1;
        private java.awt.Panel panel1;
        private java.awt.ScrollPane scrollPane1;
        private org.jdesktop.beansbinding.BindingGroup bindingGroup;
        // End of variables declaration//GEN-END:variables
}
