package lookandfeeldemo;

import java.awt.GridLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

public class LookAndFeelFrame extends javax.swing.JFrame {

   private UIManager.LookAndFeelInfo[] looks;
   private String[] lookNames;
   private JRadioButton[] radio;
   private ButtonGroup group;
   private JButton button;
   private JLabel label;
   private JComboBox comboBox;
   
   public LookAndFeelFrame(){
       super("Look and Feel Demo");
       
       looks = UIManager.getInstalledLookAndFeels();
       lookNames = new String[looks.length];
       
       for(int i=0; i<looks.length;i++)
           lookNames[i] = looks[i].getName();
       
       JPanel northPanel = new JPanel();
       northPanel.setLayout(new GridLayout(3, 1, 0, 5));
       
       label = new JLabel("This is a "+ lookNames[0] + " look and feel",
               SwingConstants.CENTER);
       northPanel.add(label);
       
       button = new JButton("JButton");
       northPanel.add(button);
       
       comboBox = new JComboBox(lookNames);
       northPanel.add(comboBox);
       
       radio = new JRadioButton[looks.length];
       
       JPanel southPanel = new JPanel();
       
       int rows = (int)Math.ceil(radio.length/3.0);
       southPanel.setLayout(new GridLayout(rows,3));
       
       group = new ButtonGroup();
       ItemHandler handler = new ItemHandler() {};
       
       for(int count=0; count<radio.length; count++)
       {
           radio[count] = new JRadioButton(lookNames[count]);
           radio[count].addItemListener(handler);
           southPanel.add(radio[count]);
       }
       
       add(northPanel);
       add(southPanel);
       
       radio[0].setSelected(true);       
       
       
   }
   
     private void changeTheLookAndFeel(int value)
       {
           try{
               UIManager.setLookAndFeel(looks[value].getClassName());
               
               SwingUtilities.updateComponentTreeUI(this);
           }catch(Exception exception)
           {
            exception.printStackTrace();
           }
       }
     
     public abstract class ItemHandler implements ItemListener
     {
         public void itemStateChanged(ItemEvent event)
         {
             for(int count=0; count < radio.length; count++)
             {
                 if(radio[count].isSelected())
                 {
                     label.setText(String.format("This is a %s look and feel", lookNames[count]));
                     comboBox.setSelectedIndex(count);
                     changeTheLookAndFeel(count);
                 }
             }
         }
     }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LookAndFeelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LookAndFeelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LookAndFeelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LookAndFeelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LookAndFeelFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
