/*
 * JavaGUI_009_Klasor_Dosya_İslemleriView.java
 */

package javaguı_009_klasor_dosya_islemleri;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * The application's main frame.
 */
public class JavaGUI_009_Klasor_Dosya_İslemleriView extends FrameView {

    public JavaGUI_009_Klasor_Dosya_İslemleriView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = JavaGUI_009_Klasor_Dosya_İslemleriApp.getApplication().getMainFrame();
            aboutBox = new JavaGUI_009_Klasor_Dosya_İslemleriAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        JavaGUI_009_Klasor_Dosya_İslemleriApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                mainPanel = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jButton4 = new javax.swing.JButton();
                jButton5 = new javax.swing.JButton();
                jPanel2 = new javax.swing.JPanel();
                jButton6 = new javax.swing.JButton();
                jButton7 = new javax.swing.JButton();
                jButton8 = new javax.swing.JButton();
                jButton9 = new javax.swing.JButton();
                jButton10 = new javax.swing.JButton();
                jPanel3 = new javax.swing.JPanel();
                jButton11 = new javax.swing.JButton();
                jButton12 = new javax.swing.JButton();
                jPanel4 = new javax.swing.JPanel();
                jButton13 = new javax.swing.JButton();
                jButton14 = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                jTextField1 = new javax.swing.JTextField();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTextPane1 = new javax.swing.JTextPane();
                menuBar = new javax.swing.JMenuBar();
                javax.swing.JMenu fileMenu = new javax.swing.JMenu();
                javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
                javax.swing.JMenu helpMenu = new javax.swing.JMenu();
                javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
                statusPanel = new javax.swing.JPanel();
                javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
                statusMessageLabel = new javax.swing.JLabel();
                statusAnimationLabel = new javax.swing.JLabel();
                progressBar = new javax.swing.JProgressBar();

                mainPanel.setName("mainPanel"); // NOI18N

                org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(javaguı_009_klasor_dosya_islemleri.JavaGUI_009_Klasor_Dosya_İslemleriApp.class).getContext().getResourceMap(JavaGUI_009_Klasor_Dosya_İslemleriView.class);
                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel1.border.titleFont"), resourceMap.getColor("jPanel1.border.titleColor"))); // NOI18N
                jPanel1.setName("jPanel1"); // NOI18N

                jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
                jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
                jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton1.setName("jButton1"); // NOI18N
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jButton2.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
                jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
                jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton2.setName("jButton2"); // NOI18N
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                jButton3.setIcon(resourceMap.getIcon("jButton3.icon")); // NOI18N
                jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
                jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton3.setName("jButton3"); // NOI18N
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                jButton4.setIcon(resourceMap.getIcon("jButton4.icon")); // NOI18N
                jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
                jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton4.setName("jButton4"); // NOI18N
                jButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton4ActionPerformed(evt);
                        }
                });

                jButton5.setIcon(resourceMap.getIcon("jButton5.icon")); // NOI18N
                jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
                jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton5.setName("jButton5"); // NOI18N
                jButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton5ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton2)
                                        .addComponent(jButton3)
                                        .addComponent(jButton4)
                                        .addComponent(jButton5)
                                        .addComponent(jButton1))
                                .addContainerGap(80, Short.MAX_VALUE))
                );

                jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, jButton5});

                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addContainerGap(15, Short.MAX_VALUE))
                );

                jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel2.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel2.border.titleFont"), resourceMap.getColor("jPanel2.border.titleColor"))); // NOI18N
                jPanel2.setName("jPanel2"); // NOI18N

                jButton6.setIcon(resourceMap.getIcon("jButton6.icon")); // NOI18N
                jButton6.setText(resourceMap.getString("jButton6.text")); // NOI18N
                jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton6.setName("jButton6"); // NOI18N
                jButton6.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton6ActionPerformed(evt);
                        }
                });

                jButton7.setIcon(resourceMap.getIcon("jButton7.icon")); // NOI18N
                jButton7.setText(resourceMap.getString("jButton7.text")); // NOI18N
                jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton7.setName("jButton7"); // NOI18N
                jButton7.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton7ActionPerformed(evt);
                        }
                });

                jButton8.setIcon(resourceMap.getIcon("jButton8.icon")); // NOI18N
                jButton8.setText(resourceMap.getString("jButton8.text")); // NOI18N
                jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton8.setName("jButton8"); // NOI18N
                jButton8.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                jButton9.setIcon(resourceMap.getIcon("jButton9.icon")); // NOI18N
                jButton9.setText(resourceMap.getString("jButton9.text")); // NOI18N
                jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton9.setName("jButton9"); // NOI18N
                jButton9.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton4ActionPerformed(evt);
                        }
                });

                jButton10.setIcon(resourceMap.getIcon("jButton10.icon")); // NOI18N
                jButton10.setText(resourceMap.getString("jButton10.text")); // NOI18N
                jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton10.setName("jButton10"); // NOI18N
                jButton10.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton5ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton6)
                                        .addComponent(jButton7)
                                        .addComponent(jButton8)
                                        .addComponent(jButton9)
                                        .addComponent(jButton10))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton10, jButton6, jButton7, jButton8, jButton9});

                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel3.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel3.border.titleFont"), resourceMap.getColor("jPanel3.border.titleColor"))); // NOI18N
                jPanel3.setName("jPanel3"); // NOI18N

                jButton11.setIcon(resourceMap.getIcon("jButton11.icon")); // NOI18N
                jButton11.setText(resourceMap.getString("jButton11.text")); // NOI18N
                jButton11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton11.setName("jButton11"); // NOI18N
                jButton11.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton11ActionPerformed(evt);
                        }
                });

                jButton12.setIcon(resourceMap.getIcon("jButton12.icon")); // NOI18N
                jButton12.setText(resourceMap.getString("jButton12.text")); // NOI18N
                jButton12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton12.setName("jButton12"); // NOI18N
                jButton12.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton12ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton12)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
                jPanel4.setName("jPanel4"); // NOI18N

                jButton13.setIcon(resourceMap.getIcon("jButton13.icon")); // NOI18N
                jButton13.setText(resourceMap.getString("jButton13.text")); // NOI18N
                jButton13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton13.setName("jButton13"); // NOI18N
                jButton13.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton13ActionPerformed(evt);
                        }
                });

                javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(javaguı_009_klasor_dosya_islemleri.JavaGUI_009_Klasor_Dosya_İslemleriApp.class).getContext().getActionMap(JavaGUI_009_Klasor_Dosya_İslemleriView.class, this);
                jButton14.setAction(actionMap.get("quit")); // NOI18N
                jButton14.setIcon(resourceMap.getIcon("jButton14.icon")); // NOI18N
                jButton14.setText(resourceMap.getString("jButton14.text")); // NOI18N
                jButton14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jButton14.setName("jButton14"); // NOI18N

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton13))
                                .addContainerGap(20, Short.MAX_VALUE))
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap(45, Short.MAX_VALUE)
                                .addComponent(jButton13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton14)
                                .addContainerGap())
                );

                jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
                jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
                jLabel1.setName("jLabel1"); // NOI18N

                jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
                jTextField1.setName("jTextField1"); // NOI18N

                jScrollPane1.setName("jScrollPane1"); // NOI18N

                jTextArea1.setColumns(20);
                jTextArea1.setRows(5);
                jTextArea1.setName("jTextArea1"); // NOI18N
                jScrollPane1.setViewportView(jTextArea1);

                jScrollPane2.setName("jScrollPane2"); // NOI18N

                jTextPane1.setName("jTextPane1"); // NOI18N
                jScrollPane2.setViewportView(jTextPane1);

                javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
                mainPanel.setLayout(mainPanelLayout);
                mainPanelLayout.setHorizontalGroup(
                        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2)))
                );
                mainPanelLayout.setVerticalGroup(
                        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 197, Short.MAX_VALUE))
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                                .addGap(11, 11, 11)
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane2))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                );

                menuBar.setName("menuBar"); // NOI18N

                fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
                fileMenu.setName("fileMenu"); // NOI18N

                exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
                exitMenuItem.setName("exitMenuItem"); // NOI18N
                fileMenu.add(exitMenuItem);

                menuBar.add(fileMenu);

                helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
                helpMenu.setName("helpMenu"); // NOI18N

                aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
                aboutMenuItem.setName("aboutMenuItem"); // NOI18N
                helpMenu.add(aboutMenuItem);

                menuBar.add(helpMenu);

                statusPanel.setName("statusPanel"); // NOI18N

                statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

                statusMessageLabel.setName("statusMessageLabel"); // NOI18N

                statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

                progressBar.setName("progressBar"); // NOI18N

                javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
                statusPanel.setLayout(statusPanelLayout);
                statusPanelLayout.setHorizontalGroup(
                        statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
                        .addGroup(statusPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(statusMessageLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 914, Short.MAX_VALUE)
                                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusAnimationLabel)
                                .addContainerGap())
                );
                statusPanelLayout.setVerticalGroup(
                        statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(statusPanelLayout.createSequentialGroup()
                                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(statusMessageLabel)
                                        .addComponent(statusAnimationLabel)
                                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3))
                );

                setComponent(mainPanel);
                setMenuBar(menuBar);
                setStatusBar(statusPanel);
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               String dosyamizinYolu = DosyaIslemleri.dosyaSecMetodu();
	       
	       if(dosyamizinYolu != null){
		       jTextField1.setText(dosyamizinYolu);
	       }
		
        }//GEN-LAST:event_jButton1ActionPerformed

        private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
              
		 String dosyamizinYolu = DosyaIslemleri.klasorSecMetodu();
	       
	       if(dosyamizinYolu != null){
		       jTextField1.setText(dosyamizinYolu);
	       }
		
        }//GEN-LAST:event_jButton6ActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                File olustur = new File(jTextField1.getText());
		
		String sonuc = DosyaIslemleri.dosyaOlusturmaMetodu(olustur);
		if(sonuc.equalsIgnoreCase("ONAYLANDI")){
			JOptionPane.showMessageDialog(mainPanel,sonuc,"Bilgi Mesajı",JOptionPane.INFORMATION_MESSAGE);
		}else{
			JOptionPane.showMessageDialog(mainPanel,sonuc,"Hata Mesajı",JOptionPane.ERROR_MESSAGE);
		}
		
        }//GEN-LAST:event_jButton2ActionPerformed

        private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                 File olustur = new File(jTextField1.getText());
		
		String sonuc = DosyaIslemleri.klasorOlusturmaMetodu(olustur);
		if(sonuc.equalsIgnoreCase("ONAYLANDI")){
			JOptionPane.showMessageDialog(mainPanel,sonuc,"Bilgi Mesajı",JOptionPane.INFORMATION_MESSAGE);
		}else{
			JOptionPane.showMessageDialog(mainPanel,sonuc,"Hata Mesajı",JOptionPane.ERROR_MESSAGE);
		}
		
        }//GEN-LAST:event_jButton7ActionPerformed

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                String koplanacakYer = DosyaIslemleri.klasorSecMetodu();
		if(koplanacakYer == null){
			JOptionPane.showMessageDialog(mainPanel, "Lütfen Bir Adres Seçiniz: ", "Bilgi Mesajı", JOptionPane.INFORMATION_MESSAGE);
			return;
		}
		String kopyalanacakDosyaVeyaDizi = jTextField1.getText();
		File kaynak = new File(kopyalanacakDosyaVeyaDizi);
		File hedef = new File(koplanacakYer);
		
		try{
			DosyaIslemleri.kopyalamaMetodu(kaynak, hedef);
			JOptionPane.showMessageDialog(mainPanel, "İşlem Tamamdır: ", "Bilgi Mesajı", JOptionPane.INFORMATION_MESSAGE);
		}catch(Exception e){
			JOptionPane.showMessageDialog(mainPanel, "Hata Oluştu", "Hata Mesajı", JOptionPane.ERROR_MESSAGE);
		}
		
        }//GEN-LAST:event_jButton3ActionPerformed

        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                String tasinaciYer = DosyaIslemleri.klasorSecMetodu();
		
		if(tasinaciYer == null){
		JOptionPane.showMessageDialog(mainPanel, "Lütfen Bir Adres Seçiniz ", "Bilgi Mesajı", JOptionPane.INFORMATION_MESSAGE);	
		return;
		}
		
		String tasinacakDosyaveDizin = jTextField1.getText();
		File kaynak = new File(tasinacakDosyaveDizin);
		File hedef = new File(tasinaciYer);
		
		String netice = DosyaIslemleri.tasimaMetodu(kaynak, hedef);
		
		if(netice.equalsIgnoreCase("Onaylandı")){
			JOptionPane.showMessageDialog(mainPanel, netice,"Bilgi Mesajı", JOptionPane.INFORMATION_MESSAGE);
		}else{
				JOptionPane.showMessageDialog(mainPanel, netice,"Hata Mesajı", JOptionPane.ERROR_MESSAGE);
		}
		
        }//GEN-LAST:event_jButton4ActionPerformed

        private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                int gelenDeger = JOptionPane.showConfirmDialog(mainPanel, "Silmek İçin Eminmisiniz?", "Uyarı", JOptionPane.YES_NO_OPTION);
		
		if(gelenDeger == JOptionPane.YES_OPTION){
			File silinecek = new File(jTextField1.getText());
			String netice = DosyaIslemleri.silmeMetodu(silinecek);
			
			if(netice.equalsIgnoreCase("Onaylandı")){
				JOptionPane.showMessageDialog(mainPanel, netice, "Bilgi Mesajı", JOptionPane.INFORMATION_MESSAGE);
			}else{
				JOptionPane.showMessageDialog(mainPanel, netice, "Hata Mesajı", JOptionPane.ERROR_MESSAGE);
			}
		}else if(gelenDeger == JOptionPane.NO_OPTION){
			return;
			
		}
		
        }//GEN-LAST:event_jButton5ActionPerformed

        private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
                if(jTextField1.getText().trim().length() == 0){
			JOptionPane.showMessageDialog(mainPanel, "Lütfen Bir Adres Seçiniz", "Bilgi Mesajı", JOptionPane.INFORMATION_MESSAGE);
			return;
		}
		
		File dosya = new File(jTextField1.getText());
		if(dosya.exists() == false){
			JOptionPane.showMessageDialog(mainPanel, "seçilen Yolda Dosya Bulunamadı", "Bilgi Mesajı", JOptionPane.INFORMATION_MESSAGE);
			return ;
		}
		
		try{
	             System.out.println(DosyaIslemleri.dosyaOkumaMetodu(dosya));	
		     jTextArea1.setText(DosyaIslemleri.dosyaOkumaMetodu(dosya).toString());
		     jTextPane1.setText(DosyaIslemleri.dosyaOkumaMetodu(dosya).toString());
		}catch(Exception e){
			JOptionPane.showMessageDialog(mainPanel, "Hata Oluştu", "Hata Mesajı", JOptionPane.ERROR_MESSAGE);
		}
        }//GEN-LAST:event_jButton11ActionPerformed

        private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
               
		if(jTextField1.getText().trim().length() == 0){
			JOptionPane.showMessageDialog(jTextPane1, "YazılacakDosyasınızı Seçmeniz Gerekmektedir.", "Bilgi Mesajı", JOptionPane.INFORMATION_MESSAGE);
			return;
		}
		String[][] kayitlar = {
			{"Uğur","Arı","1994"},
			{"Zülfiye","Arı","1996"},
			{"Muhammet Ali","Arı","2005"}
		};
		
		List<String> yazdiracaklar = new ArrayList<String>();
		for(String[] dizimiz : kayitlar){
			yazdiracaklar.add(dizimiz[0]+" - "+ dizimiz[1]+ " ");
		}
		
		int gelenDeger = JOptionPane.showConfirmDialog(mainPanel, "Yazdıralacak içerik dosyay sondan eklensin mi?"+"\nHayır, bu dosyadaki tüm içeriği sil\nbenim belirtiğim isimleri ekle","Uyarı Mesajı", JOptionPane.YES_NO_OPTION);
		
		   try{
			  
			if(gelenDeger == JOptionPane.YES_OPTION){
				DosyaIslemleri.dosyaYazmaMetodu(yazdiracaklar, new File(jTextField1.getText()), true);
			}else if(gelenDeger == JOptionPane.NO_OPTION){
				DosyaIslemleri.dosyaYazmaMetodu(yazdiracaklar, new File(jTextField1.getText()), false);
				
				JOptionPane.showMessageDialog(mainPanel, "Onaylandı","Bilgi Mesajı", JOptionPane.INFORMATION_MESSAGE);
			
			JOptionPane.showMessageDialog(mainPanel, "Hata MEsajı", "Hata Mesajı", JOptionPane.ERROR_MESSAGE);
				
				}
		
		   }catch(Exception e){
			   
		   }
		
        }//GEN-LAST:event_jButton12ActionPerformed

        private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
                jTextArea1.setText(null);
		jTextField1.setText(null);
		jTextPane1.setText(null);
        }//GEN-LAST:event_jButton13ActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton10;
        private javax.swing.JButton jButton11;
        private javax.swing.JButton jButton12;
        private javax.swing.JButton jButton13;
        private javax.swing.JButton jButton14;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JButton jButton5;
        private javax.swing.JButton jButton6;
        private javax.swing.JButton jButton7;
        private javax.swing.JButton jButton8;
        private javax.swing.JButton jButton9;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTextArea jTextArea1;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextPane jTextPane1;
        private javax.swing.JPanel mainPanel;
        private javax.swing.JMenuBar menuBar;
        private javax.swing.JProgressBar progressBar;
        private javax.swing.JLabel statusAnimationLabel;
        private javax.swing.JLabel statusMessageLabel;
        private javax.swing.JPanel statusPanel;
        // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
